companieshouse/acsp-manage-users-web

- src/lib/utils/environmentValue.ts
- test/src/lib/utils/environment.value.test.ts
- test/src/setup.ts
Link to Jira:
https://companieshouse.atlassian.net/browse/IDVA6-1298
Changes:
- getEnvironmentValue throws an error if a key that is being fetched does not exist.
> IDVA6 1298 Add user api - throw error if environment variable does not exist

- src/views/manage-users.njk
Add length checks for administratorsTableData and standardUsersTableData to prevent rendering empty tables in the manage-users view.
> IDVA6-1343: Check for non-empty user data before rendering tables

- src/lib/constants.ts
- src/locales/cy/translation/try-adding-user.json
- src/locales/en/translation/try-adding-user.json
- src/routers/controllers/tryAddingUserController.ts
- src/routers/router.ts
- src/views/check-member-details.njk
- src/views/placeholder-stop-screen.njk
- test/mocks/acsp.members.mock.ts
- test/mocks/user.mock.ts
- test/src/routers/controllers/tryAddingUserController.test.ts
- Convert GET to POST for try-adding-user endpoint
- Implement actual user addition logic in tryAddingUserControllerPost
- Add error handling and stop screen for various failure scenarios
- Update tests to cover new logic and error cases
- Create mock data helpers for ACSP members and users
- Add placeholder stop screen view for error cases
- Update constants and translations for new error handling
- Modify check-member-details view to use POST form submission
- Update router to use new POST controller
> IDVA6-1359: Refactor try-adding-user flow and improve test coverage

- src/middleware/i18next.language.ts
- test/src/routers/controllers/dashboardController.test.ts
Link to Jira
https://companieshouse.atlassian.net/browse/IDVA6-1428
Currently the language choice is being saved in a cookie. This PR updates the i18next configuration to both detect and save the user’s preferred language to the session.
> IDVA6-1428 update i18next middleware config to use session

- src/app.ts
- test/src/routers/router.test.ts
Link to Jira
https://companieshouse.atlassian.net/browse/IDVA6-1433
We have a middleware function that retrieves ACSP member logged in user details.
Its saves these details to the session so that individual pages do not need to request them.
The PR updates this so that we only fetch the member details on /authorised-agent requests, rather than all requests.
> IDVA6-1433 get logged in user details middleware update

- assets/src/scss/__global.scss
- assets/src/scss/govuk-language-select.scss
- src/app.ts
- src/locales/cy/translation/common.json
- src/locales/en/translation/common.json
- src/types/language.ts
- src/views/partials/nav/top.njk
- Add language selector in top navigation
- Implement language switching logic in Express middleware
- Create LANGUAGE_CONFIG with supported languages (English and Welsh)
- Add SCSS styles for language selector
- Update app.ts to handle language selection and URL modification
- Introduce new type definition for language configuration
This change introduces multi-language support to the application, allowing users to switch between English and Welsh. The language selector is added to the top navigation, and the necessary backend logic is implemented to handle language switching and URL modifications.
> IDVA6-1390: Implement language selection functionality

- src/locales/cy/translation/try-adding-user.json
- src/locales/en/translation/try-adding-user.json
- src/routers/controllers/addUserController.ts
- src/routers/controllers/checkMemberDetailsController.ts
- src/routers/controllers/confirmationMemberAddedController.ts
- src/routers/controllers/tryAddingUserController.ts
- test/src/routers/controllers/addUserController.test.ts
- test/src/routers/controllers/checkMemberDetailsController.test.ts
- test/src/routers/controllers/confirmationMemberAdded.test.ts
- test/src/routers/controllers/tryAddingUserController.test.ts
- Update page title for "You cannot add this user" page
- Fix back link on "Cannot add user" page to return to Check Details page
- Redirect users without CH accounts to stop page instead of placeholder
- Replace hardcoded ACSP names with dynamic `acspName` from user membership
- Remove hardcoded user roles, use actual roles from ACSP membership
- Refactor to use ACSP membership data consistently across controllers
- Update tests to reflect these changes
This change addresses issues raised in IDVA6-1436 and IDVA6-1431, improving the user experience and data accuracy when adding new members to an ACSP. It ensures correct page navigation, displays appropriate error messages, and uses real ACSP and user data instead of hardcoded values.
> IDVA6-1436, IDVA6-1435: Improve user flow and data accuracy in member addition process

- src/lib/utils/viewUtils.ts
- src/views/manage-users.njk
- test/src/lib/utils/viewUtils.test.ts
- test/src/routers/controllers/manageUsersController.getViewData.test.ts
**Changes made:**
Adding Matomo Analytics for:
- Add a user
- Remove
- Account owner Tab
- Administrator Tab
- Standard User Tab
- updated tests
Link to ticket: https://companieshouse.atlassian.net/browse/IDVA6-1405
> IDVA6-1405: Adding Matomo Analytics For Manage User Page

- src/locales/cy/translation/common.json
- src/locales/en/translation/common.json
- src/views/confirmation-member-added.njk
- src/views/confirmation-member-removed.njk
- src/views/confirmation-you-are-removed.njk
- Add "success" string to English and Welsh translation files
- Update notification banners in member addition/removal confirmations
- Set "Success" as the title for these notification banners (translated)
> IDVA6-1461: Add "Success" title to notification banners

- src/locales/cy/translation/cannot-add-user.json
- src/locales/cy/translation/check-member-details.json
- src/locales/cy/translation/common.json
- src/locales/cy/translation/stop-page-add-account-owner.json
- src/locales/en/translation/cannot-add-user.json
- src/locales/en/translation/check-member-details.json
- src/locales/en/translation/common.json
- src/locales/en/translation/stop-page-add-account-owner.json
- test/src/routers/controllers/cannotAddUserController.test.ts
- test/src/routers/controllers/checkMemberDetailsController.test.ts
- Added 'back_link' to common.json in both English and Welsh translations
- Removed redundant 'back_link' entries from: (already present in common.json)
- check-member-details.json
- cannot-add-user.json
- stop-page-add-account-owner.json
- Removed redundant 'back_link_to_the_previous_page' from cannot-add-user.json (already present in common.json)
This change improves maintainability by centralizing common translations and reducing duplication across JSON files. The 'back_link' text will now be sourced from common.json and can be overridden in specific views if needed.  There is no need to override if it's the same value, so those have been removed.
> IDVA6-1501: Centralize 'back_link' in common.json and remove duplicates

- src/routers/controllers/manageUsersController.ts
- src/views/add-user.njk
- src/views/partials/__footer.njk
- src/views/partials/__header.njk
- test/src/routers/controllers/manageUsersController.search.test.ts
- Ensures pagination still works upon a search failure, we default to page 1
- We also ensure normal results show when a search fails, rather than we have "no" "admin/owner/standard"
- Note, a valid search should only have 1 result, so no need for pagination there
- Fix bullet point styling on add user page (just adding some classes)
- Ensure the header/title of the page shows, it was referencing the wrong translation
https://companieshouse.atlassian.net/browse/IDVA6-1518
Edit: pushed https://github.com/companieshouse/acsp-manage-users-web/pull/97/commits/eebf8f6234a4a33563c99b14dc5da6b259dcebeb to handle scenario where we scroll when the page loads initially
> IDVA6-1518: Fix multiple bugs

- tools/README.md
- tools/seed-acsp-data-mongo/README.md
- tools/seed-acsp-data-mongo/config.js
- tools/seed-acsp-data-mongo/index.js
- tools/seed-acsp-data-mongo/package-lock.json
- tools/seed-acsp-data-mongo/package.json
Add MongoDB seed tool for ACSP test data
- Generates fake users, ACSP profiles, and members
- Configurable via env vars and config file
- Supports multiple MongoDB environments
- Located in tools/seed-acsp-data-mongo
Originally from https://github.com/bmchugh-ch - but modified to work with `acsp_profile.acsp_profile`.
> IDVA6-1572: Tools dir and acsp data seeding tool

- src/middleware/navigationMiddleware.ts
- test/src/middleware/navigation.middleware.test.ts
**JIRA LINK**
https://companieshouse.atlassian.net/browse/IDVA6-1961
Added redirect for view and manage users.
Admin / account owners are automatically redirected from the view-users page (to the manage-users page) .
Standard users are redirected to view users when trying to access manage users.
**Unit test**
Updated navigation.middleware.test.ts
> IDVA6-1961 Redirect View And Manage Users

- test/src/app.test.ts
- test/src/routers/controllers/addUserController.test.ts
- test/src/routers/controllers/cannotAddUserController.test.ts
- test/src/routers/controllers/checkEditMemberRoleDetailsController.test.ts
- test/src/routers/controllers/checkMemberDetailsController.test.ts
- test/src/routers/controllers/confirmationMemberAdded.test.ts
- test/src/routers/controllers/confirmationMemberRoleEditedController.test.ts
- test/src/routers/controllers/csrErrorController.test.ts
- test/src/routers/controllers/dashboardController.test.ts
- test/src/routers/controllers/editMemberRoleController.test.ts
- test/src/routers/controllers/healthCheckContorller.test.ts
- test/src/routers/controllers/httpErrorController.test.ts
- test/src/routers/controllers/manageUsersController.pagination.test.ts
- test/src/routers/controllers/manageUsersController.search.test.ts
- test/src/routers/controllers/manageUsersController.test.ts
- test/src/routers/controllers/removeUserCheckDetailsController.test.ts
- test/src/routers/controllers/removeUserSuccessController.test.ts
- test/src/routers/controllers/stopPageAddOwnerControllerGet.test.ts
- test/src/routers/controllers/stopPageController.test.ts
- test/src/routers/controllers/tryAddingUserController.test.ts
- test/src/routers/controllers/tryEditMemberRoleController.test.ts
- test/src/routers/controllers/tryRemovingUserController.test.ts
- test/src/routers/router.test.ts
Investigated and fixing integration test memory leaks warnings by mocking the Logger using Jest.
This warnings was appearing in the console/terminals and this PR fixes it and it no longer shows the warnings of the terminal/console.
`(node:34503) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 uncaughtException listeners added to [process]. MaxListeners is 10. Use emitter.setMaxListeners() to increase limit
(Use `node --trace-warnings ...` to show where the warning was created)`
> IDVA6-2069-Investigate and Fixing Integration Test Memory Leaks Warnings

- src/routers/controllers/manageUsersController.ts
- test/src/routers/controllers/manageUsersController.search.test.ts
https://companieshouse.atlassian.net/browse/IDVA6-2162
When  searching for a user (who is not on the most recent manage users page) and you try to remove or change role for the user the page errors as this user (who was searched for) is not found in the session.
This PR fixes the above issue by ensuring any searched for user is saved to the session.
> IDVA6-2161 Save manage user search results to the session

- src/routers/controllers/manageUsersController.ts
When standard users are logged in and they click on pagination buttons (next, previous, 1..2) they are incorrectly redirected to the manage-users page rather than view-users.
Link to Jira
https://companieshouse.atlassian.net/browse/IDVA6-2288
> IDVA6-2288 Bug: Standard users - pagination buttons should link to view-users not manage-users

- src/views/manage-users.njk
There is an error appearing in the browser logs when matomo tries to track the remove and add user goals and the logged in user is a standard user. 
This PR ensures that the event listeners are only added when the user is an admin or owner.
https://companieshouse.atlassian.net/browse/IDVA6-2294
> IDVA6-2294 Disable tracking remove, add user goals for standard users

- src/views/partials/dashboard/verify_someones_identity.njk
- test/src/routers/controllers/dashboardController.test.ts
Link to Jira:
https://companieshouse.atlassian.net/browse/IDVA6-2396
Changes:
- Added query string logic to "Verifying someone's identity" link to continue same language throughout service
> IDVA6-2396 - Continue Language Throughout Services

- src/views/partials/__header.njk
**Jira link:**
https://companieshouse.atlassian.net/browse/IDVA6-2265
**Changes:**
- Made changes so Tell us what you think of Companies House survey link should **not** open a new tab by changing target=_blank to target=_self.
> IDVA6-2265 Survey Link Should Not Open New Tab

- src/middleware/content.security.policy.middleware.config.ts
**Jira**
https://companieshouse.atlassian.net/browse/SIV-524
After forms are submitted, the auth service sometimes redirects to HTTP urls, which is blocked by our CSP.
This PR updates the CSP to allow forms to submit and redirect to http://CHS_URL
> SIV-524 update CSP: allow http, https chs url form submissions, redirects
