src/app.ts
src/lib/constants.ts
src/router.dispatch.ts
src/views/partials/service_unavailable.njk

Link to Jira:
https://companieshouse.atlassian.net/browse/IDVA6-1175
Changes:
- Service unavailable template added
- Data type on error parameter changed from any to Error

IDVA6-1175 service unavailable page

---

assets/src/scss/__global.scss
src/app.ts
src/locales/cy/translation/common.json
src/locales/en/translation/common.json
src/views/layouts/default.njk
src/views/layouts/shell.njk
src/views/partials/__footer.njk
src/views/partials/customer_insights.njk

Link to Jira:
https://companieshouse.atlassian.net/browse/IDVA6-1190
Changes:
- Footer bar updated

IDVA6-1190 Footer bar

---

assets/src/scss/__global.scss
gulpfile.js
package-lock.json
package.json
src/app.ts
src/views/layouts/default.njk
src/views/layouts/shell.njk
src/views/partials/__footer.njk

Link to Jira:
https://companieshouse.atlassian.net/browse/IDVA6-1253
Changes:
- govuk-frontend package updated to the newest version
- Code updated to work with the newest version of govuk-frontend

IDVA6-1253 update gouk-frontend to newest version

---

README.md

Remove the web starter readme.

Remove web starter readme

---

src/middleware/authentication.middleware.ts
src/routers/controllers/healthCheckController.ts
src/routers/router.ts
test/src/routers/healthCheckContorller.test.ts

Link to Jira:
https://companieshouse.atlassian.net/browse/IDVA6-1285
Changes:
Adds health check end point

IDVA6-1285 add health check end point

---

src/app.ts

Link to Jira:
https://companieshouse.atlassian.net/browse/IDVA6-1321
Changes:
- Environment variable changed to a correct one

IDVA6-1321 Resources not loading in phoenix1

---

package-lock.json
src/lib/constants.ts
src/lib/utils/viewUtils.ts
src/locales/cy/translation/check-member-details.json
src/locales/cy/translation/common.json
src/locales/cy/translation/manage-users.json
src/locales/en/translation/check-member-details.json
src/locales/en/translation/common.json
src/locales/en/translation/manage-users.json
src/routers/controllers/checkMemberDetailsController.ts
src/routers/controllers/tryAddingUserController.ts
src/routers/router.ts
src/types/userRole.ts
src/types/userRoleTag.ts
src/views/check-member-details.njk
test/mocks/user.mock.ts
test/src/routers/controllers/checkMemberDetailsController.test.ts
test/src/routers/controllers/dashboardController.test.ts
test/src/routers/controllers/healthCheckContorller.test.ts
test/src/routers/controllers/manageUsersController.test.ts
test/src/routers/controllers/tryAddingUserController.test.ts
test/src/routers/manageUsersController.test.ts

Link to Jira:
https://companieshouse.atlassian.net/browse/IDVA6-1181
Changes:
- Session utilities added
- Check member details page created
- Temporary code added to allow testing until the API is available

IDVA6-1181 check the details before you add the user page

---

src/views/partials/dashboard/verify_someones_identity.njk

Link to Jira
https://companieshouse.atlassian.net/browse/IDVA6-1295
Changes:
- Fix to box structure

IDVA6-1295 Agent Dashboard - Version 3.1

---

src/routers/controllers/addUserController.ts
src/types/utilTypes.ts
src/views/add-user.njk
test/src/routers/controllers/addUserController.test.ts

Link to Jira:
https://companieshouse.atlassian.net/browse/IDVA6-1188
Changes:
- UserRole enum added as a global variable to Nunjucks
- Radio buttons displayed based on the role of the logged in user
- Tests updated and new added

IDVA6-1188 show different radio buttons based on roles

---

src/locales/cy/translation/confirmation-member-removed.json
src/locales/en/translation/confirmation-member-removed.json
src/routers/controllers/removeUserSuccessController.ts
src/routers/router.ts
src/views/confirmation-member-removed.njk
test/src/routers/removeUserSuccessController.test.ts

Link to Jira:
https://companieshouse.atlassian.net/browse/IDVA6-1198
Changes:
- Added design and page functionality for remove user success page
- Adde unit tests for remove user success page

IDVA6-1198 - Remove user success page

---

src/locales/en/translation/common.json
src/routers/controllers/manageUsersController.ts
src/views/manage-users.njk
test/src/routers/controllers/manageUsersController.test.ts

Link to Jira:
https://companieshouse.atlassian.net/browse/IDVA6-1187
Changes:
- Logged in user role added
- Remove column shown based on user role
- Tests updated

IDVA6-1187 show remove link based on roles

---

src/lib/constants.ts
src/services/apiClientService.ts

https://companieshouse.atlassian.net/browse/IDVA6-1298
Update api key name for fetching user details.

IDVA6-1298 update api key name

---

package-lock.json
package.json
src/services/acspMemberService.ts
src/services/apiClientService.ts
test/mocks/acsp.members.mock.ts
test/src/services/acspMemberService.createAcspMembership.test.ts
test/src/services/acspMemberService.getAcspMembers.test.ts
test/src/services/acspMemberService.getMembershipForLoggedInUser.test.ts
test/src/services/acspMemberService.updateOrRemoveUserAcspMembership.test.ts

Link to Jira
https://companieshouse.atlassian.net/browse/IDVA6-1342
Adds services to interact with ACSP manage users api and updates private-api-sdk-node package.

IDVA6-1342 ACSP manage users service

---

src/lib/constants.ts
test/src/routers/controllers/dashboardController.test.ts
test/src/routers/controllers/manageUsersController.getViewData.test.ts

Link to Jira:
https://companieshouse.atlassian.net/browse/IDVA6-1395
Changes:
- The route for the dashboard changed
- Unit tests updated

IDVA6-1395 change route for the dashboard

---

src/lib/constants.ts
src/locales/cy/translation/confirmation-you-are-removed.json
src/locales/en/translation/confirmation-you-are-removed.json
src/routers/controllers/confirmationYouAreRemovedController.ts
src/routers/controllers/removeUserCheckDetailsController.ts
src/routers/controllers/tryRemovingUserController.ts
src/routers/router.ts
src/types/membership.ts
src/views/confirmation-member-removed.njk
src/views/confirmation-you-are-removed.njk
test/src/routers/controllers/confirmationYouAreRemovedController.test.ts
test/src/routers/controllers/tryRemovingUserController.test.ts

URL
https://companieshouse.atlassian.net/browse/IDVA6-1316
Adds a remove yourself success page.

IDVA6 1316 Remove themselves success page

---

src/services/acspMemberService.ts
test/src/services/acspMemberService.getAcspMembershipForMemberId.test.ts
test/src/services/acspMemberService.membershipLookup.test.ts

Link to Jira
https://companieshouse.atlassian.net/browse/IDVA6-1342
Adds requests to ACSP manage users API for 
- lookup based on user email for a specific ACSP
- getting acsp membership for acsp_number and membership_id

IDVA6-1342 add api service functions for membership lookup checks

---

src/locales/cy/translation/manage-users.json
src/locales/en/translation/manage-users.json
src/routers/controllers/manageUsersController.ts
src/views/manage-users.njk
src/views/partials/__meta_header.njk

Conditional statement to check if a user is an owner or admin then show add user button and manage users, if the user is a standard user then show view user and hide add user button.
**Before**
**After**

IDVA6-1343 Hide Add User Button

---

src/routers/controllers/manageUsersController.ts
src/routers/controllers/tryAddingUserController.ts
src/routers/controllers/tryRemovingUserController.ts
src/services/acspMemberService.ts
src/types/membership.ts
src/views/confirmation-member-removed.njk
src/views/remove-member.njk
test/mocks/acsp.members.mock.ts
test/mocks/user.mock.ts
test/src/routers/controllers/helpers/removeThemselvesHelper.test.ts
test/src/routers/controllers/manageUsersController.getViewData.test.ts
test/src/routers/controllers/manageUsersController.test.ts
test/src/routers/removeUserCheckDetailsController.test.ts
test/src/routers/removeUserSuccessController.test.ts

URL
https://companieshouse.atlassian.net/browse/IDVA6-1245
Adds api integration for the manage users page

IDVA6-1245 Manage users api integration

---

src/app.ts
src/lib/constants.ts
src/lib/utils/sessionUtils.ts
src/middleware/loggedUserAcspMembership.middleware.ts
src/routers/controllers/dashboardController.ts
test/mocks/acsp.members.mock.ts
test/mocks/all.middleware.mock.ts
test/mocks/loggedUserAcspMembershipMiddleware.middleware.mock.ts
test/src/lib/utils/sessionUtils.test.ts
test/src/middleware/loggedUserAcspMembership.middleware.test.ts
test/src/routers/controllers/addUserController.test.ts
test/src/routers/controllers/confirmationMemberAdded.test.ts
test/src/routers/controllers/dashboardController.test.ts
test/src/routers/controllers/manageUsersController.test.ts
test/src/routers/controllers/tryAddingUserController.test.ts
test/src/routers/controllers/tryRemovingUserController.test.ts
test/src/routers/removeUserCheckDetailsController.test.ts
test/src/routers/removeUserSuccessController.test.ts
test/src/routers/router.test.ts
test/src/services/acspMemberService.createAcspMembership.test.ts
test/src/services/acspMemberService.getAcspMembers.test.ts
test/src/services/acspMemberService.getAcspMembershipForMemberId.test.ts
test/src/services/acspMemberService.getMembershipForLoggedInUser.test.ts
test/src/services/acspMemberService.membershipLookup.test.ts

Link to Jira:
https://companieshouse.atlassian.net/browse/IDVA6-1272
Changes:
- Hardcoded data replaced with data from session
- Logged user ACSP membership middleware and relevant session utility method added
- Unit tests updated and new added

IDVA6-1272 api integration for agent dashboard

---

package-lock.json
package.json
src/lib/constants.ts
src/locales/cy/translation/manage-users.json
src/locales/en/translation/manage-users.json
src/routers/controllers/manageUsersController.ts
src/routers/router.ts
src/views/manage-users.njk
src/views/partials/__footer.njk
test/mocks/acsp.members.mock.ts
test/src/middleware/loggedUserAcspMembership.middleware.test.ts
test/src/routers/controllers/manageUsersController.getViewData.test.ts
test/src/routers/controllers/manageUsersController.search.test.ts
test/src/routers/controllers/manageUsersController.test.ts
test/src/routers/controllers/removeUserCheckDetailsController.test.ts
test/src/routers/controllers/removeUserSuccessController.test.ts
test/src/services/acspMemberService.getAcspMembers.test.ts
test/src/services/acspMemberService.getMembershipForLoggedInUser.test.ts

Link to Jira:
https://companieshouse.atlassian.net/browse/IDVA6-1274
Changes:
- Search functionality added
- Page not loading after clicking View users link in the dashboard error fixed
- Mocks and tests updated and new added
- Misplaced files with tests moved to the correct directory

IDVA6-1274 manage user search

---

src/routers/controllers/removeUserCheckDetailsController.ts
src/routers/router.ts
src/views/remove-member.njk

**Changes:**
- adding POST to removeUserCheckDetails endpoint to redirect
- update router to use new POST controller
- refactored remove-member.njk file
Link to ticket - https://companieshouse.atlassian.net/browse/IDVA6-1370

IDVA6-1370 Form Submit Bug Fix 

---

src/routers/controllers/removeUserCheckDetailsController.ts
src/views/remove-member.njk
test/src/routers/controllers/removeUserCheckDetailsController.test.ts
test/src/routers/controllers/removeUserCheckDetailsController.unit.test.ts

Link to Jira
https://companieshouse.atlassian.net/browse/IDVA6-1403
Updates the display name in the check details before you remove page.

IDVA6 1403 check details before you remove page - update display name

---

package-lock.json
package.json
src/app.ts
src/lib/constants.ts
src/locales/cy/translation/stop-page-add-account-owner.json
src/locales/en/translation/stop-page-add-account-owner.json
src/routers/controllers/manageUsersController.ts
src/routers/controllers/stopPageAddOwnerControllerGet.ts
src/views/stop-page-add-account-owner.njk
test/src/routers/controllers/stopPageAddOwnerControllerGet.test.ts

Link to Jira
https://companieshouse.atlassian.net/browse/IDVA6-1404
Update stop screen when the only owner is removing themselves to include a back button and a details component 
Update Axios to the latest version

IDVA6 1404 Update stop screen when the only owner is removing themselves

---

src/views/manage-users.njk

Removing ACSP company number
**Link to ticket:** https://companieshouse.atlassian.net/browse/IDVA6-1426
**Before**
**After:**

IDVA6-1343-Bug-Fix-Removing ACSP company number

---

src/lib/constants.ts
src/lib/utils/urlUtils.ts
src/middleware/authentication.middleware.ts
src/middleware/loggedUserAcspMembership.middleware.ts
test/src/lib/utils/urlUtils.test.ts
test/src/middleware/loggedUserAcspMembership.middleware.test.ts

Link to Jira
https://companieshouse.atlassian.net/browse/IDVA6-1433
Updates loggedUserAcspMemberhip middleware function to ignore requests for /healthcheck

IDVA6-1433 Update loggedUserAcspMemberhip to allow healthcheck

---

src/app.ts

Link to Jira
https://companieshouse.atlassian.net/browse/IDVA6-1433
Fixes incorrect middleware order in app.ts

IDVA6-1433 fix incorrect middleware order

---

src/views/dashboard.njk

https://companieshouse.atlassian.net/browse/IDVA6-1402
Updates the order of dashboard items.

IDVA6-1402 change order of boxes on the dashboard page

---

src/views/partials/dashboard/manage_users.njk
src/views/partials/dashboard/update_authorised_agent_details.njk
src/views/partials/dashboard/verify_someones_identity.njk
src/views/partials/dashboard/view_users.njk

https://companieshouse.atlassian.net/browse/IDVA6-1399
Add role based data event id attributes to the links on the dashboard page for Matomo tracking.

IDVA6-1399 Add Matomo events for links on /authorised-agent dashboard page

---

src/views/confirmation-member-removed.njk
src/views/confirmation-you-are-removed.njk
src/views/remove-member.njk
src/views/stop-page-add-account-owner.njk

https://companieshouse.atlassian.net/browse/IDVA6-1407
Add Matomo (data-event-id) tags for the remove-member page, the remove member success page, remove yourself success page and the stop page when user is the only owner and removing themselves.

IDVA6 1407 Add analytics for remove member and remove yourself flow

---

src/routers/controllers/manageUsersController.ts
src/views/partials/__footer.njk

Link to Jira:
https://companieshouse.atlassian.net/browse/IDVA6-1442
Changes:
- The search input preserved
- Fix to the problem with scrolling to search result in mobile view and uncaught type error
- Fix to the problem with hash part from previous search result

IDVA6-1442 bug fix for IDVA6-1274

---

src/app.ts
src/lib/utils/userRoleUtils.ts
src/views/dashboard.njk
src/views/partials/dashboard/manage_users.njk
src/views/partials/dashboard/update_authorised_agent_details.njk
src/views/partials/dashboard/verify_someones_identity.njk
src/views/partials/dashboard/view_users.njk
test/src/lib/utils/userRoleUtils.test.ts

https://companieshouse.atlassian.net/browse/IDVA6-1399
Update the wording of the user role for Matomo event actions and updates page title

IDVA6 1455 update Matomo tags for dashboard page

---

src/views/add-user.njk

https://companieshouse.atlassian.net/browse/IDVA6-1406
Add Matomo tracking for the add user radio button

IDVA6-1406 add-user radio button tracking

---

src/middleware/i18next.language.ts

Duplicate of https://github.com/companieshouse/your-companies-web/pull/172 for acsp-manage-users-web

BAU: Fix directory structure locale loading

---

src/middleware/navigationMiddleware.ts
src/types/navigation.ts
test/src/middleware/navigation.middleware.test.ts

https://companieshouse.atlassian.net/browse/IDVA6-1515
**Changes**
- Update the navigation middleware (bookmarks redirect) to check user role permissions.
- Updates the redirect page for the confirmation page when a user removes themselves.

IDVA6-1515 Update navigation checks to include user role

---

src/lib/utils/sessionUtils.ts
src/routers/controllers/addUserController.ts
test/src/lib/utils/sessionUtils.test.ts

Link to Jira:
https://companieshouse.atlassian.net/browse/IDVA6-1467
Changes:
- Unnecessary imports removed
- "Unexpected any" issue indicated by Lint fixed
- Additional unit tests added

IDVA6-1467 refactoring

---

src/app.ts
src/routers/controllers/manageUsersController.ts
src/routers/controllers/tryAddingUserController.ts

Link to Jira:
https://companieshouse.atlassian.net/browse/IDVA6-1467
Changes:
- Unnecessary type assertions removed
- Duplicated import removed

Feature/idva6 1467 refactoring - sonar qube issues fixes

---

src/routers/controllers/tryAddingUserController.ts

Link to Jira:
https://companieshouse.atlassian.net/browse/IDVA6-1467
Changes:
- Unnecessary import removed

IDVA6-1467 Unnecessary import removed

---

src/routers/controllers/dashboardController.ts

Link to Jira:
https://companieshouse.atlassian.net/browse/IDVA6-1516
Changes:
- Fix to missing menu item after login

IDVA6-1516 Bug fix for IDVA6-1177

---

package-lock.json

Link to Jira:
https://companieshouse.atlassian.net/browse/IDVA6-1560
Changes:
- Vulnerabilities in dependencies fixed

IDVA6-1560 Vulnerabilities in dependencies fixed

---

test/src/app.test.ts
test/src/lib/utils/environmentValue.test.ts

Link to Jira:
https://companieshouse.atlassian.net/browse/IDVA6-1467
Changes:
- Additional unit tests added to improve test coverage

IDVA6-1467 Additional unit tests to improve test coverage

---

src/routers/controllers/manageUsersController.ts
src/server.ts
src/views/add-user.njk
test/src/routers/controllers/manageUsersController.search.test.ts

**Warning - do not merge until https://github.com/companieshouse/acsp-manage-users-web/pull/101 is merged.**
**This is based on top of it, and once https://github.com/companieshouse/acsp-manage-users-web/pull/101 is merged it should automatically re-target main.**
---
- Optimize user search logic to handle found and not found cases
- Adjust pagination behavior for search results
- Update bullet point styling in add-user view for better indentation
- Fix issue with displaying default text for empty role tabs
Screenshot show styling change:
Video showing pagination:
https://github.com/user-attachments/assets/f6963015-682e-41f7-950e-6ac7c53856df

IDVA6-1518: Refactor user search and improve UI in manage users page

---

src/routers/controllers/manageUsersController.ts
src/server.ts
src/views/add-user.njk
test/src/routers/controllers/manageUsersController.search.test.ts

https://github.com/companieshouse/acsp-manage-users-web/pull/102 was merged into a sub branch, not main.
This PR targets and will be merged into main.

Duplicate of https://github.com/companieshouse/acsp-manage-users-web/pull/102

---

src/middleware/content.security.policy.middleware.config.ts

https://companieshouse.atlassian.net/browse/IDVA6-1576
Update to use different CDN env value

IDVA6-1576 change cdn env value

---

src/routers/controllers/manageUsersController.ts

- Improve code structure and readability
- Fix bug: invalid email searches now return empty results
This change re-arranges the conditional logic, to ensure that if a search is performed with an invalid email, we show the default search results (as if no search was performed), instead of empty search results.

IDVA6-1518: Refactor manageUsersController and fix invalid email search

---

src/app.ts
src/lib/utils/translationUtils.ts
src/router.dispatch.ts
src/routers/controllers/addUserController.ts
src/routers/controllers/cannotAddUserController.ts
src/routers/controllers/checkMemberDetailsController.ts
src/routers/controllers/confirmationMemberAddedController.ts
src/routers/controllers/confirmationYouAreRemovedController.ts
src/routers/controllers/dashboardController.ts
src/routers/controllers/httpErrorController.ts
src/routers/controllers/manageUsersController.ts
src/routers/controllers/removeUserCheckDetailsController.ts
src/routers/controllers/removeUserSuccessController.ts
src/routers/controllers/stopPageAddOwnerControllerGet.ts
src/types/@types/express/index.d.ts
tsconfig.json

Link to Jira:
https://companieshouse.atlassian.net/browse/IDVA6-1631
Changes:
- Request type extended with lang property
- Project configuration updated to use added extension to Request type
- Code refactored to remove unnecessary casting to any and string
- No longer needed imports removed

IDVA6-1631 Extend request type to contain lang property

---

src/views/confirmation-member-added.njk
test/src/routers/controllers/confirmationMemberAdded.test.ts

Link to Jira:
https://companieshouse.atlassian.net/browse/IDVA6-1664
Changes:
- Strings in both sides of the condition changed to lower case to ensure correct result of comparison 
- Tests refactored to increase coverage

IDVA6-1664 Wrong article used in confirmation for adding a user for ACSP

---

src/lib/constants.ts

Link to Jira:
https://companieshouse.atlassian.net/browse/IDVA6-1581
Changes:
- Placeholder URL replaced with the actual service URL

IDVA6-1581 add CH verify identity link to manage users web

---

src/lib/constants.ts
src/lib/utils/environmentValue.ts
src/routers/controllers/manageUsersController.ts

https://companieshouse.atlassian.net/browse/IDVA6-1570
Add some logging for tracking / troubleshooting env variables

IDVA6-1570 Add logging for env variables

---

src/lib/constants.ts
src/middleware/navigationMiddleware.ts
src/routers/controllers/tryRemovingUserController.ts
test/src/middleware/navigation.middleware.test.ts

[Link to Jira](https://companieshouse.atlassian.net/browse/IDVA6-1672)
Adds a check in navigation middleware, to ensure that a user, who has removed themselves can longer access the front end pages.

IDVA6-1672 Prevent access for users who have removed themselves 

---

src/app.ts
src/lib/constants.ts
src/lib/validation/clear.form.validation.ts
src/routers/controllers/addUserController.ts
src/routers/controllers/manageUsersController.ts
test/src/routers/controllers/addUserController.test.ts
test/src/routers/controllers/manageUsersController.getViewData.test.ts

Link to Jira:
https://companieshouse.atlassian.net/browse/IDVA6-1702
Changes:
- Added functionality to prevent form data being cleared if user has switched language on 'add-user' page
- Added unit test for new lines

IDVA6-1702 - Bug Fix - Language change removes 'add a user' page errors

---

jest.config.ts
locales/cy/service-unavailable.json
locales/en/service-unavailable.json
src/app.ts
src/lib/constants.ts
src/lib/utils/environmentValue.ts
src/middleware/csrf.protection.middleware.ts
src/middleware/session.middleware.ts
src/routers/controllers/errorController.ts
src/routers/controllers/manageUsersController.ts
src/routers/controllers/stopPageController.ts
src/routers/router.ts
src/views/add-user.njk
src/views/check-member-details.njk
src/views/manage-users.njk
src/views/partials/csrf_token.njk
src/views/partials/service_unavailable.njk
src/views/remove-member.njk
test/mocks/all.middleware.mock.ts
test/mocks/csrf.protection.middleware.mock.ts
test/src/routers/controllers/csrErrorController.test.ts
test/src/routers/controllers/stopPageController.test.ts

**JIRA link**
https://companieshouse.atlassian.net/browse/IDVA6-1630
**Change description**
CSRF token implementation to prevent CSRF attacks.
- Implementation of CSRF middleware from web-security-node
- Add the CSRF token to each page with a <form method="post"> element.
- Update error page to handle CSRF errors

IDVA6-1630 Add CSRF mitigation

---

src/routers/controllers/checkMemberDetailsController.ts
src/views/check-member-details.njk
test/src/routers/controllers/checkMemberDetailsController.test.ts

Link to Jira
https://companieshouse.atlassian.net/browse/IDVA6-1718
- Updates the name of the email on check the details page.
- Update unit test to check for both logged in email and new user email.

IDVA6-1718 Update email on check the details page

---

src/routers/controllers/errorController.ts
test/src/routers/controllers/invalidAcspNumberErrorController.test.ts

https://companieshouse.atlassian.net/browse/IDVA6-1707
Updates. the InvalidAcspNumberError handler to include the logged in user email.

IDVA6-1707 Add logged in email to InvalidAcspNumberError handler

---

package-lock.json
package.json

Link to Jira:
https://companieshouse.atlassian.net/browse/IDVA6-1763
Changes:
- Dependencies bumped to newer versions to fix vulnerabilities

IDVA6-1763 Fix vulnerabilities in dependencies

---

src/lib/constants.ts
src/middleware/navigationMiddleware.ts
src/routers/controllers/tryRemovingUserController.ts
test/src/middleware/navigation.middleware.test.ts
test/src/routers/controllers/tryRemovingUserController.test.ts

Link to Jira:
https://companieshouse.atlassian.net/browse/IDVA6-1746
Changes:
- Added sign out url constant
- Updated referrer policy to allow for sign out upon removal of own account

IDVA6-1746 - Logout user who removes themselves

---

src/routers/controllers/addUserController.ts

Changes:
- adding comment for test trigger build

Test Trigger Build

---

README.md
docs/Handling errors.md
src/routers/controllers/tryEditMemberRoleController.ts
test/src/routers/controllers/tryEditMemberRoleController.test.ts

Link to Jira
https://companieshouse.atlassian.net/browse/IDVA6-1794
Add additional information to the readme

IDVA6-1794 update readme

---

README.md

Link to Jira:
https://companieshouse.atlassian.net/browse/IDVA6-1837
Changes:
- Spelling fixed

IDVA6-1837 Spelling fixed

---

src/app.ts
src/lib/constants.ts
test/src/app.test.ts

Link to Jira:
https://companieshouse.atlassian.net/browse/IDVA6-1837
Changes:
- Code duplication in tests removed
- Hard coded strings replaced with constants

IDVA6-1837 Code refactored

---

Makefile

Link to Jira:
https://companieshouse.atlassian.net/browse/IDVA6-1843
Changes:
- Test added to sonar prior to run sunarqube to fix problem with statistics not displayed for main branch

IDVA6-1843 Fix to SonarQube not showing statistics for main branch

---

package-lock.json

Link to Jira:
https://companieshouse.atlassian.net/browse/IDVA6-1912
Changes:
- Updated package json file

IDVA6-1912 - user not being logged out

---

package-lock.json
package.json

Link to Jira:
https://companieshouse.atlassian.net/browse/IDVA6-1950
Changes:
- Dependencies updated to use the latest version navbar common component

IDVA6-1950 Dependencies updated

---

src/lib/constants.ts
src/routers/controllers/dashboardController.ts

Link to Jira:
https://companieshouse.atlassian.net/browse/IDVA6-1959
Changes:
- Feature flag added to hide href in a link until the service is live

IDVA6-1959 Flag verify someone link in ACSP dashboard

---

src/lib/constants.ts
src/routers/controllers/dashboardController.ts

Link to Jira:
https://companieshouse.atlassian.net/browse/IDVA6-1988
Changes:
- Feature flag added and URL updated

IDVA6-1988 Feature flag a link in ACSP Manage Users dashboard

---

locales/cy/confirmation-member-removed.json
locales/en/confirmation-member-removed.json
src/views/confirmation-member-removed.njk
test/src/routers/controllers/removeUserSuccessController.test.ts

Link to Jira:
https://companieshouse.atlassian.net/browse/IDVA6-1621
Changes:
- Updated content on 'confirmation member removed' page
- Updated language files for member removed
- Updated relevant unit tests

IDVA6-1621 - Remove User content

---

locales/cy/edit-member-role.json
locales/en/edit-member-role.json
src/routers/controllers/editMemberRoleController.ts
src/views/edit-member-role.njk
test/src/routers/controllers/editMemberRoleController.test.ts

Link to Jira:
https://companieshouse.atlassian.net/browse/IDVA6-2029
Changes:
- Updated language files with new page content
- Updated controller to remove unnecessary content
- Updated unit tests

IDVA6-2029 - updating edit user role page content

---

src/routers/controllers/editMemberRoleController.ts

Link to Jira:
https://companieshouse.atlassian.net/browse/IDVA6-2052
Changes:
- Removed unneeded interface elements that caused errors in deployment

IDVA6-2053 - Bug Fix - EditMemberRoleViewData missing properties

---

src/lib/utils/urlUtils.ts
src/middleware/navigationMiddleware.ts
src/routers/controllers/editMemberRoleController.ts

Link to Jira:
https://companieshouse.atlassian.net/browse/IDVA6-2056
Changes:
- Code smells indicated by SonarQube removed

IDVA6-2056 Remove code smells indicated by SonarQube

---

src/routers/controllers/manageUsersController.ts
test/src/routers/controllers/manageUsersController.search.test.ts

Link to Jira:
https://companieshouse.atlassian.net/browse/IDVA6-2052
Changes:
- Added logic to update search url depending on user role
- Updated unit tests

IDVA6-2052 - Bug Fix - Acsp manage users Search is not working for Standard user

---

src/middleware/navigationMiddleware.ts
src/routers/controllers/editMemberRoleController.ts

Link to Jira:
https://companieshouse.atlassian.net/browse/IDVA6-2059
Changes:
- Missing URL added to allowed referrers
- Code reformatted to make it more readable

IDVA6-2059 Change role for account owner does not work

---

src/middleware/csrf.protection.middleware.ts
test/src/middleware/csrf.middleware.test.ts

https://companieshouse.atlassian.net/browse/IDVA6-2083
Adds whitelist for the CSRF middleware to ignore health check requests

IDVA6-1154 Add health check exception to CSRF middleware

---

src/views/check-edit-member-role-details.njk

Link to Jira:
https://companieshouse.atlassian.net/browse/IDVA6-2089
Changes:
- Updated template to account for word order differences between welsh and english

IDVA6-2089 - Bug fix - check edit member details page

---

locales/cy/confirmation-you-are-removed.json
locales/cy/dashboard.json
locales/cy/manage-users.json
locales/en/confirmation-you-are-removed.json
locales/en/dashboard.json
locales/en/manage-users.json

Link to Jira:
https://companieshouse.atlassian.net/browse/IDVA6-889
Changes:
- Minor updates to language files
- Removing unused language files

IDVA6-889 - acsp manage users - minor changes

---

sonar-project.properties

Update to sonar-project.properties

---

src/views/manage-users.njk

Jira ticket:
https://companieshouse.atlassian.net/browse/IDVA6-2239
Changes:
- maxlength attribute added to email input field

IDVA6-2239 Max length added to email input field

---

locales/cy/access-denied.json

Link to Jira:
https://companieshouse.atlassian.net/browse/IDVA6-2281
Changes:
- CY tag removed from texts in the Welsh language json file

IDVA6-2281 CY tag removed from texts in the Welsh language json file

---

src/middleware/loggedUserAcspMembership.middleware.ts
src/routers/controllers/errorController.ts

Link to Jira:
https://companieshouse.atlassian.net/browse/IDVA6-2342
Changes:
- Exception from logged user acsp membership middleware added for access denied page

IDVA6-2342 Redirection loop happens in life environment

---

package-lock.json

Link to Jira:
https://companieshouse.atlassian.net/browse/IDVA6-2343
Changes:
- Fix to vulnerabilities in dependencies

IDVA6-2343 Fix to vulnerabilities in dependencies

---

src/middleware/loggedUserAcspMembership.middleware.ts

Link to Jira:
https://companieshouse.atlassian.net/browse/IDVA6-2342
Changes:
- Previously added additional condition is removed as no longer needed

IDVA6-2342 Reverting a change to loggedUserAcspMembershipMiddleware

---

locales/cy/access-denied.json
locales/en/access-denied.json
src/views/access-denied.njk
test/src/routers/controllers/accessDeniedController.test.ts

Link to Jira:
https://companieshouse.atlassian.net/browse/SIV-124
Changes:
- Updated page structure and language files to reflect design changes in prototype
- Updated unit tests to account for updated content

SIV-124 - Manage users stop screen content changes

---

src/lib/Logger.ts
src/routers/controllers/accessDeniedController.ts
src/routers/controllers/addUserController.ts
src/routers/controllers/cannotAddUserController.ts
src/routers/controllers/checkEditMemberRoleDetailsController.ts
src/routers/controllers/checkMemberDetailsController.ts
src/routers/controllers/confirmationMemberAddedController.ts
src/routers/controllers/confirmationMemberRoleEditedController.ts
src/routers/controllers/dashboardController.ts
src/routers/controllers/editMemberRoleController.ts
src/routers/controllers/errorController.ts
src/routers/controllers/manageUsersController.ts
src/routers/controllers/removeUserCheckDetailsController.ts
src/routers/controllers/removeUserSuccessController.ts
src/routers/controllers/somethingWentWrongController.ts
src/routers/controllers/stopPageAddOwnerControllerGet.ts
src/routers/controllers/tryAddingUserController.ts
src/routers/controllers/tryEditMemberRoleController.ts
src/routers/controllers/tryRemovingUserController.ts
src/services/acspMemberService.ts
src/services/userAccountService.ts

https://companieshouse.atlassian.net/browse/IDVA6-2344
- Adds logging when rendering a page
- Removes any PII

IDVA6-2344 remove PII, add rendering logs

---

src/lib/helpers/acspLogger.ts
src/middleware/navigationMiddleware.ts
src/routers/controllers/addUserController.ts
src/routers/controllers/cannotAddUserController.ts
src/routers/controllers/checkEditMemberRoleDetailsController.ts
src/routers/controllers/checkMemberDetailsController.ts
src/routers/controllers/confirmationMemberAddedController.ts
src/routers/controllers/confirmationMemberRoleEditedController.ts
src/routers/controllers/dashboardController.ts
src/routers/controllers/editMemberRoleController.ts
src/routers/controllers/errorController.ts
src/routers/controllers/manageUsersController.ts
src/routers/controllers/removeUserCheckDetailsController.ts
src/routers/controllers/removeUserSuccessController.ts
src/routers/controllers/somethingWentWrongController.ts
src/routers/controllers/stopPageAddOwnerControllerGet.ts
src/routers/controllers/tryAddingUserController.ts
src/routers/controllers/tryEditMemberRoleController.ts
src/routers/controllers/tryRemovingUserController.ts
src/services/acspMemberService.ts
test/src/lib/helpers/acspLogger.test.ts

Improve logging information:  include acspNumber, userid and role.
https://companieshouse.atlassian.net/browse/IDVA6-2344

IDVA6-2344 Add more information when logging

---

src/services/userAccountService.ts

**Link to JIRA**
https://companieshouse.atlassian.net/browse/IDVA6-2344
Removes unnecessary logs, where ACSP user details are not provided.

IDVA6-2344 remove unneeded logs in userAccountService

---

src/lib/constants.ts
src/routers/controllers/dashboardController.ts
src/views/partials/dashboard/verify_someones_identity.njk
test/src/routers/controllers/dashboardController.test.ts

https://companieshouse.atlassian.net/browse/SIV-136
**Changes**
Feature flag added to enable a link to /tell-companies-house-you-have-verified-someones-identity

SIV-136 Feature flag for link to tell Companies House you've verified someones identity

---

src/middleware/content.security.policy.middleware.config.ts

https://companieshouse.atlassian.net/browse/IDVA6-2359
Updates content security policy to allow CDN in connect src.

IDVA6-2359 Allow CDN connectSrc in content security policy

---

locales/cy/dashboard.json
locales/en/dashboard.json
src/views/partials/dashboard/verify_someones_identity.njk

https://companieshouse.atlassian.net/browse/SIV-136
Update tell companies house you've verified someones identity text on dashboard

SIV-136 Update tell companies house you've verified someones identity

---

assets/src/scss/__global.scss
src/views/accessibility-statement.njk

https://companieshouse.atlassian.net/browse/IDVA6-2364
- Added CSS of margin-bottom of 5px to fix the issue in mobile view.

IDVA6-1351 Bug Fix For Mobile View List

---

package.json
src/lib/constants.ts
src/lib/utils/sessionUtils.ts
src/services/acspMemberService.ts
src/services/apiCallRetryService.ts
src/services/apiClientService.ts
src/services/refreshTokenService.ts
test/mocks/session.mock.ts
test/src/lib/utils/sessionUtils.test.ts
test/src/services/acspMemberService.createAcspMembership.test.ts
test/src/services/acspMemberService.getAcspMembers.test.ts
test/src/services/acspMemberService.getAcspMembershipForMemberId.test.ts
test/src/services/acspMemberService.getMembershipForLoggedInUser.test.ts
test/src/services/acspMemberService.membershipLookup.test.ts
test/src/services/acspMemberService.updateOrRemoveUserAcspMembership.test.ts
test/src/services/apiClientService.test.ts
test/src/services/refreshTokenService.test.ts
tsconfig.json

Link to Jira:
https://companieshouse.atlassian.net/browse/SIV-129
Changes:
- Functions for refreshing oauth token and API call with retry added

SIV-129 401 from live when users try to get members of acsp

---

src/routers/controllers/manageUsersController.ts

https://companieshouse.atlassian.net/browse/IDVA6-2353
- Removing display query param from the URL and displaySearch property

IDVA6-2353 Removing Display Query From URL and Display Search

---

src/routers/controllers/editMemberRoleController.ts
src/routers/controllers/removeUserCheckDetailsController.ts

Link to Jira:
https://companieshouse.atlassian.net/browse/IDVA6-2380
Changes:
- Added logic to prevent treating Welsh translation of 'Not provided' as a username but display user email instead

IDVA6-2380 - Bug Fix - User email not being used

---

locales/cy/dashboard.json
locales/en/dashboard.json
src/views/dashboard.njk
test/src/routers/controllers/dashboardController.test.ts

Link to Jira:
https://companieshouse.atlassian.net/browse/IDVA6-2401
Changes:
- Updated logic and relevant tests to allow for correct English and Welsh guidance links

IDVA6-2401 - Bug Fix - Guidance Link

---

src/lib/helpers/acspLogger.ts
src/lib/utils/sessionUtils.ts
src/routers/controllers/errorController.ts
test/mocks/session.mock.ts
test/src/lib/utils/sessionUtils.test.ts
test/src/routers/controllers/errorController.invalidAcspNumberErrorHandler.test.ts

Link to Jira:
https://companieshouse.atlassian.net/browse/IDVA6-2403
Changes:
- Function added to retrieve user ID from the session
- User ID added to a log entry for `invalidAcspNumberErrorHandler` function

IDVA6-2403 Logging improved for invalidAcspNumberErrorHandler function

---

src/routers/controllers/addUserController.ts
test/src/routers/controllers/addUserController.test.ts

https://companieshouse.atlassian.net/browse/IDVA6-2416
We need to ensure user input emails are lower case for consistently when creating or querying users.

IDVA6-2416 Ensure input emails are lower case on the add user page

---

README.md
test/src/app.test.ts

Description
Update readme to re run the pipeline
Link to Jira
https://companieshouse.atlassian.net/browse/IDVA6-2416

IDVA6-2416 update readme

---

src/routers/controllers/manageUsersController.ts
test/src/services/acspMemberService.membershipLookup.test.ts
test/src/services/acspMemberService.updateOrRemoveUserAcspMembership.test.ts

Link to Jira:
https://companieshouse.atlassian.net/browse/IDVA6-2415
Changes:
- Conditions for displaying change role and remove user links fixed
- Code refactored to improve variable naming

IDVA6-2415 change role and remove user shown to wrong user in search result

---

src/views/dashboard.njk

Link to ticket: https://companieshouse.atlassian.net/browse/IDVA6-2264
Changes:
Removing govuk-!-margin-right-2

IDVA6-2264 removing margin right

---

package-lock.json
package.json

Link to Jira:
https://companieshouse.atlassian.net/browse/IDVA6-2263
Changes:
- ch-node-utils version updated

IDVA6-2263 ch-node-utils version updated

---

assets/src/scss/__global.scss

https://companieshouse.atlassian.net/browse/IDVA6-2431
Increases line height for navbar links to 1.6
Changes the width breakpoint for customer insights CSS class

IDVA6-2431 Update CSS for navbar and customer insights

---

nodemon.json
package-lock.json
package.json
src/bin/nodemon-entry.ts

Link to Jira:
https://companieshouse.atlassian.net/browse/IDVA6-2451
Changes:
- Added relevant nodemon files and scripts from troubleshooting docs
- Updated package json with suggested lines

IDVA6-2451 - Configuring Nodemon for Development in ACSP

---

src/routers/controllers/dashboardController.ts
src/routers/controllers/stopPageAddOwnerControllerGet.ts

Link to Jira:
https://companieshouse.atlassian.net/browse/IDVA6-2454
Changes:
- Language parameter added to the URL to ensure that the service the link points to keeps the same language version

IDVA6-2454 Language parameter added to the URL

---

package-lock.json
package.json
src/routers/controllers/tryEditMemberRoleController.ts
src/services/acspMemberService.ts
test/mocks/acsp.members.mock.ts
test/src/services/acspMemberService.updateOrRemoveUserAcspMembership.test.ts

Link to Jira:
https://companieshouse.atlassian.net/browse/SIV-203
Changes:
- Code refactored to incorporate changes in node API client

SIV-203 Code refactored to incorporate changes in node API client

---

src/services/apiClientService.ts

Link to Jira:
https://companieshouse.atlassian.net/browse/SIV-244
Changes:
- Updated the private api client parameters

SIV-244 - Update API Client Parameters 

---

src/lib/constants.ts
src/routers/controllers/manageUsersController.ts
src/services/apiClientService.ts

**Link to Jira:**
https://companieshouse.atlassian.net/browse/IDVA6-2472
**Changes**:
- Removes Promise.all withhin manage users controller, those manage users api calls are now individual await requests.
- Updates createOAuthApiClient to use  env variable ACCOUNT_LOCAL_URL as the base url

IDVA6 2472 Update refresh token config

---

locales/cy/cannot-add-user.json
locales/en/cannot-add-user.json
src/lib/constants.ts
src/routers/controllers/cannotAddUserController.ts
src/views/cannot-add-user.njk
test/src/routers/controllers/cannotAddUserController.test.ts

Link to Jira:
https://companieshouse.atlassian.net/browse/SIV-284
Changes:
- Page content updated to follow the prototype https://find-update-company-info.herokuapp.com/authorised-agent-v8/alt-add-user/interrupt-user-already-added-alt#main-content

SIV-284 update with newly updated content

---

locales/cy/before-you-add-user.json
locales/en/before-you-add-user.json
src/lib/constants.ts
src/middleware/navigationMiddleware.ts
src/routers/controllers/addUserController.ts
src/routers/controllers/beforeYouAddUserController.ts
src/routers/controllers/manageUsersController.ts
src/routers/router.ts
src/views/add-user.njk
src/views/before-you-add-user.njk
test/src/middleware/navigation.middleware.test.ts
test/src/routers/controllers/addUserController.test.ts
test/src/routers/controllers/beforeYouAddUserController.test.ts
test/src/routers/controllers/manageUsersController.getViewData.test.ts

Link to Jira:
https://companieshouse.atlassian.net/browse/SIV-278
Changes:
- the new page added

SIV-278 interrupt page before adding a user

---

src/views/before-you-add-user.njk

Link to Jira:
https://companieshouse.atlassian.net/browse/SIV-289
Changes:
- The problem with redirection after the external link is clicked is fixed

SIV-289 Fix to the problem with redirection

---

package-lock.json
package.json
src/routers/controllers/tryEditMemberRoleController.ts
src/services/acspMemberService.ts
test/mocks/acsp.members.mock.ts
test/src/services/acspMemberService.updateOrRemoveUserAcspMembership.test.ts

Link to Jira:
https://companieshouse.atlassian.net/browse/SIV-274
Changes:
- Reverts companieshouse/acsp-manage-users-web#227

Revert "SIV-203 Code refactored to incorporate changes in node API client"

---

locales/cy/before-you-add-user.json
locales/cy/cannot-add-user.json

Link to Jira:
https://companieshouse.atlassian.net/browse/SIV-293
Changes:
- Welsh language files updated with the Welsh translations

SIV-293 Welsh language files updated

---

src/views/access-denied.njk
test/src/routers/controllers/accessDeniedController.test.ts

Link to Jira:
https://companieshouse.atlassian.net/browse/SIV-411
Changes:
- Updated link in both template and test files

SIV-411 - Bug Fix - ACSP Access Denied Page Registration Link

---

src/lib/constants.ts
src/services/apiClientService.ts
test/src/setup.ts

feat/cc-2678: add private load balancer

---

src/middleware/content.security.policy.middleware.config.ts
src/routers/controllers/tryRemovingUserController.ts

https://companieshouse.atlassian.net/browse/SIV-524
Allows form when signing out to submit to any url.
Removes unneeded urls from the form src allowlist - account url and the chs url.

SIV-524 allow form src to be redirected anywhere when signing out

---

src/routers/controllers/tryRemovingUserController.ts

Link to Jira
https://companieshouse.atlassian.net/browse/SIV-524
Description
Removes the content security policy header when the user is signed out.

SIV-524 Remove content security policy header on signout

---

src/app.ts

https://companieshouse.atlassian.net/browse/SIV-524
Removes the content security policy entirely for the try remove user post request.

SIV 524 Remove CSP on try remove user

---

src/lib/constants.ts
src/routers/controllers/manageUsersController.ts

Link to Jira:
https://companieshouse.atlassian.net/browse/SIV-799
Changes:
- Search parameter added to ensure search phrase is deleted from session data when not required

SIV-799 Manage users search sticking
